// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blockLoading': string;
  'container': string;
  'content': string;
  'roomList': string;
  'roomScrollWrap': string;
  'row': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
