// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'header': string;
  'hr': string;
  'partRow': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
