// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pText': string;
  'pWrap': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
