// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'border': string;
  'changeTableWrap': string;
  'charts': string;
  'completionRateWrap': string;
  'legend': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
