// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'baseWrap': string;
  'flexRow': string;
  'grid': string;
  'rightDate': string;
}
export const cssExports: CssExports;
export default cssExports;
