// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'item': string;
  'left': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
