// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'before': string;
  'bottom': string;
  'content': string;
  'dangerItem': string;
  'emptyWrap': string;
  'header': string;
  'top': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
