// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bed': string;
  'bed_number': string;
  'button': string;
  'content': string;
  'content_row': string;
  'grid': string;
  'header': string;
  'icon': string;
  'label': string;
  'mark': string;
  'person': string;
  'personContent': string;
  'personLeft': string;
  'person_content': string;
  'person_info': string;
  'roomBlock': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
