// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'overview': string;
  'overviewCol': string;
  'overviewColCenter': string;
  'overviewColNormal': string;
  'overviewItem': string;
}
export const cssExports: CssExports;
export default cssExports;
