// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card_content': string;
  'card_header': string;
  'desc': string;
  'sub_desc': string;
  'title': string;
  'version': string;
}
export const cssExports: CssExports;
export default cssExports;
