// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'day': string;
  'dayHas': string;
  'dayNoHas': string;
  'daySelected': string;
  'dayWrap': string;
  'header': string;
  'timeLineWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
