// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'age': string;
  'block': string;
  'blockItem': string;
  'blockLoading': string;
  'circle': string;
  'circle_blue': string;
  'circle_green': string;
  'circle_yellow': string;
  'colHr': string;
  'img_jianwai': string;
  'img_tanqin': string;
  'img_zaice': string;
  'img_zaitao': string;
  'img_zaiya': string;
  'img_zhuyuan': string;
  'num': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
