// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'desc': string;
  'trapeWrap': string;
  'trapezoidButton': string;
  'trapezoidButtonLast': string;
}
export const cssExports: CssExports;
export default cssExports;
