// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'circle': string;
  'spanLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
