// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dangerItem': string;
  'dangerItem_color': string;
  'dangerList': string;
}
export const cssExports: CssExports;
export default cssExports;
