// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'partRow': string;
  'table': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
