// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'changeTableWrap': string;
  'colorLabel': string;
  'selectWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
