// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'factorDetail': string;
  'radar': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
