// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'infoList': string;
  'modules': string;
}
export const cssExports: CssExports;
export default cssExports;
