// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'factor_table': string;
  'inputItem': string;
  'selectWrap': string;
  'toolbar': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
