// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colHr': string;
  'label': string;
  'summaryItem': string;
  'summaryWrap': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
