// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'healthNumber': string;
  'healthNumberItem': string;
}
export const cssExports: CssExports;
export default cssExports;
