// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemTitleWrap': string;
  'moreActions': string;
  'moreIcon': string;
  'popover': string;
  'titleWrap': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
