// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'descWrap': string;
  'numText': string;
  'progressComWrap': string;
  'progressLabel': string;
  'progressWrap': string;
  'row': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
