// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'gridWrap': string;
  'line': string;
  'record': string;
  'textRow': string;
}
export const cssExports: CssExports;
export default cssExports;
