// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'gridContent': string;
  'gridItem': string;
  'gridTableFooter': string;
  'gridTableWrap': string;
  'scrollContent': string;
}
export const cssExports: CssExports;
export default cssExports;
