// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dividing': string;
  'hr': string;
}
export const cssExports: CssExports;
export default cssExports;
