// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'card': string;
  'cardContent': string;
  'cardHeader': string;
  'container': string;
  'contentLeft': string;
  'contentRight': string;
  'icon': string;
  'inputItem': string;
  'label': string;
  'mark': string;
  'selectItem': string;
  'selectWrap': string;
  'tag': string;
  'textRow': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
