// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomBorder': string;
  'container': string;
  'extraInfo': string;
  'humanBase': string;
  'humanBody': string;
  'humanInfo': string;
  'humanWrap': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
