// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clockItem': string;
  'gridWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
