// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerItem': string;
  'headerMenu': string;
  'headerWrap': string;
  'logoTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
