// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'col': string;
  'popInfo': string;
  'row': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
