// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'before': string;
  'leftTop': string;
  'rankItem': string;
  'rankList': string;
}
export const cssExports: CssExports;
export default cssExports;
