// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'build': string;
  'infoPop': string;
  'map': string;
  'mapBg': string;
}
export const cssExports: CssExports;
export default cssExports;
