// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menuActiveWrap': string;
  'menuItemWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
