// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'crimeModalWrap': string;
  'modalWrapClass': string;
}
export const cssExports: CssExports;
export default cssExports;
