// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionWrap': string;
  'card': string;
  'cardContent': string;
  'cardHeader': string;
  'cascaderItem': string;
  'contentLeft': string;
  'contentRight': string;
  'inputItem': string;
  'selectItem': string;
  'selectWrap': string;
  'textRow': string;
  'trapeHeader': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
