// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'baseInfoWrap': string;
  'blackLabel': string;
  'content': string;
  'infoFlex': string;
  'infoItem': string;
  'nameRow': string;
}
export const cssExports: CssExports;
export default cssExports;
