// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'rec': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
